### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by echamudi** [yasirroni/myNafiun#4]
Make sure the visitors of this repo know the license:

https://choosealicense.com/

**Comment by Abdillah** [comment]
Agreed. When no license present, people would assume that they can't reuse your work before asking you the term.
If that's what you want, then no license is fine.

**Comment by echamudi** [comment]
Yes

![](https://media2.giphy.com/media/wGhYz3FHaRJgk/giphy-downsized-medium.gif)

**Comment by echamudi** [comment]
Ndi ki wong e ra muncul2 @yasirroni

**Comment by yasirroni** [comment]
Wkwk, libur sek.

**Comment by yasirroni** [comment]
Done
